[package]
name = "la_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
log_macro = "0.1.0"
markdown = "1.0.0-alpha.12"
walkdir = "2.3.3"
